### ISSUE TITLE
if not g_link

### ISSUE THREAD

**Issue by zrma** [namonak/SearchMagnet#1]
https://github.com/namonak/SearchMagnet/blob/cefc8197c8100959d50b7e181b96542dbe63d6d2/main.py#L39

@namonak 

```python
if g_link is None:
```
equal
```python
if not g_link:
```

**Comment by namonak** [comment]
조언 감사합니다~ 기존 조건문은 주석 처리하고, 알려주신 내용으로 코드 바꿨어요~
c7b189ff21077d9f3c131706c39ad4eddea3cf7a
